apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-pipeline-operator
  labels:
    app.kubernetes.io/name: "pipeline-operator"
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: concourse-operator
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "pipeline-operator"
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: concourse-operator
      controller-tools.k8s.io: "1.0"
  serviceName: {{ .Release.Name }}-pipeline-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "pipeline-operator"
        app.kubernetes.io/instance: {{ .Release.Name }}
        control-plane: concourse-operator
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: "{{ .Values.pipelineOperator.image.repository }}:{{ .Values.pipelineOperator.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Chart.Name }}
        env:
        - name: CONCOURSE_NAMESPACE_PREFIX
          value: {{ printf "%s-" .Values.global.account.name }}
        - name: CONCOURSE_ATC_ADDR
          value: https://ci.{{ .Values.global.cluster.domain }}
        - name: CONCOURSE_USERNAME
          value: {{ .Values.pipelineOperator.concourseUsername | quote }}
        - name: CONCOURSE_PASSWORD
          value: {{ .Values.pipelineOperator.concoursePassword | quote }}
        - name: CONCOURSE_INSECURE_SKIP_VERIFY
          value: {{ .Values.pipelineOperator.concourseInsecureSkipVerify | quote }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: {{ .Release.Name }}-concourse-operator-webhook
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      serviceAccountName: {{ template "pipelineOperator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-concourse-operator-webhook
